# Generated by Django 5.0.6 on 2024-06-03 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('geographic_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('construction_year', models.PositiveIntegerField()),
                ('square_footage', models.PositiveIntegerField()),
                ('representational_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.portfolio')),
            ],
        ),
    ]
